site_name: Vite Documentation
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tabs
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - tables

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

nav:
  - Overview: README.md

  - Concepts:
    - Ledger Model: 
      - vite-basics/ledger/dag-ledger.md
      - vite-basics/ledger/snapshot-chain.md
    - Consensus:
      - vite-basics/consensus/snapshot-block-producer.md
      - vite-basics/consensus/snapshot.md
      - vite-basics/consensus/voting.md
    - Cryptography:
      - vite-basics/cryptography/hash-algorithm.md
      - vite-basics/cryptography/signing.md
      - vite-basics/cryptography/address-derivation.md
    - vite-basics/token-model.md
    - vite-basics/smart-contract.md

    - Quota and Fee:
      - vite-basics/quota/quota.md
      - vite-basics/quota/fee.md

  - Network and Node:
    - vite-basics/network/introduction.md
    - vite-basics/network/nodes.md
    - vite-basics/network/setup.md
    - vite-basics/network/configuration.md
    - vite-basics/network/rpc-ipc.md
    - vite-basics/network/debug-faq.md
    - vite-basics/network/explorers.md

  - Vite API:
    - api/README.md
    - api/ledger.md
    - Contract:
      - api/contract/README.md
      - api/contract/contract.md
      - Built-in Contracts:
        - api/contract/built-in-contracts/quota.md
        - api/contract/built-in-contracts/consensus.md
        - api/contract/built-in-contracts/asset.md
    - api/wallet.md
    - api/net.md
    - api/subscribe.md
    - api/util.md

  - Vite SDK:
    - Javascript SDK:
      - SDK/vitejs/README.md
      - SDK/vitejs/providers.md
      - SDK/vitejs/viteapi-class.md
      - Wallet:
        - SDK/vitejs/wallet/README.md
        - SDK/vitejs/wallet/wallet-class.md
      - Account Block:
        - SDK/vitejs/account-block/README.md
        - SDK/vitejs/account-block/account-block-class.md
        - SDK/vitejs/account-block/account.md
        - SDK/vitejs/account-block/receive-task.md
      - SDK/vitejs/abi.md
      - SDK/vitejs/utility-funcs.md
      - SDK/vitejs/constants-and-errors.md
      - SDK/vitejs/common-patterns.md
      - SDK/vitejs/types.md
    - Java SDK:
      - SDK/vitej/README.md
      - SDK/vitej/modules/rpc.md
      - SDK/vitej/modules/wallet.md
      - SDK/vitej/modules/asset.md
      - SDK/vitej/modules/quota.md
      - SDK/vitej/modules/sbp.md
      - SDK/vitej/modules/subscribe.md
      - SDK/vitej/modules/utils.md
      - SDK/vitej/other/types.md

    - ViteConnect: SDK/vite-connect/README.md

  - Developers:
    - Solidity++ Fundamentals:
      - soliditypp/fundamentals/README.md
      - soliditypp/fundamentals/request-response-model.md
      - soliditypp/fundamentals/types.md
      - soliditypp/fundamentals/sync-async-functions.md
      - soliditypp/fundamentals/callbacks.md
      - soliditypp/fundamentals/promise-await.md
      - soliditypp/fundamentals/function-call-options.md
      - soliditypp/fundamentals/error-handling.md

      - soliditypp/fundamentals/abi.md
      - soliditypp/fundamentals/global-variables.md
      - soliditypp/fundamentals/randomness.md
      - soliditypp/fundamentals/inline-assembly.md
      - soliditypp/fundamentals/event-subscription.md

    - Compiler:
      - soliditypp/compiler/solppc-js.md

    - soliditypp/vuilder/README.md

    - IDE:
      - soliditypp/IDE/README.md
      - soliditypp/IDE/know-more.md
    
    - common-patterns/README.md
    - best-practices/README.md
    - Example Project: vite-express/README.md

  - Advanced Topics:
    - Overview: soliditypp/advanced/README.md
    - Virtual Machine Implementation:
      - soliditypp/advanced/vite-vm.md
      - soliditypp/advanced/vite-vm-instructions.md
      - soliditypp/advanced/await-operator.md
    - Vite Enhancement Proposals:
      - vep/vep-3.md
      - vep/vep-5.md
      - vep/vep-6.md
      - vep/vep-7.md
      - vep/vep-8.md
      - vep/vep-10.md
      - vep/vep-12.md
      - vep/vep-13.md
      - vep/vep-15.md
      - vep/vep-16.md
      - vep/vep-19.md
      - vep/vep-21.md

